# Generated by Django 2.2.11 on 2020-04-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('text', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
